version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    ports:
      - "65432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: my-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: mydatabase
      CLICKHOUSE_USER: myuser
      CLICKHOUSE_PASSWORD: mysecretpassword
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    networks:
      - etl-network

  cassandra:
    image: cassandra:latest
    container_name: my-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_START_RPC=true
    networks:
      - etl-network

  neo4j:
    image: neo4j:5.18
    container_name: my-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test1234
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - etl-network

  spark-jupyter:
    image: jupyter/pyspark-notebook
    container_name: spark-jupyter
    ports:
      - "9441:4040"
      - "9889:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./shared-jars:/home/jovyan/jars 
    depends_on:
      - postgres
      - clickhouse
      - cassandra
    networks:
      - etl-network

volumes:
  postgres_data:
  clickhouse_data:
  clickhouse_log:
  neo4j_data:
  neo4j_logs:


networks:
  etl-network:
    driver: bridge